/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora.view;

import java.util.Arrays;

/**
 *
 * @author HP
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jJanelaTexto = new javax.swing.JTextField();
        JBZero = new javax.swing.JButton();
        JBUm1 = new javax.swing.JButton();
        JBDois = new javax.swing.JButton();
        JBVirgula = new javax.swing.JButton();
        JBTres = new javax.swing.JButton();
        JBAdicao = new javax.swing.JButton();
        JBSubtracao = new javax.swing.JButton();
        JBResultado = new javax.swing.JButton();
        JBQuatro = new javax.swing.JButton();
        JBCinco = new javax.swing.JButton();
        JBSeis = new javax.swing.JButton();
        JBMultiplicacao = new javax.swing.JButton();
        JBSete = new javax.swing.JButton();
        JBOito = new javax.swing.JButton();
        JBNove = new javax.swing.JButton();
        JBDivisao = new javax.swing.JButton();
        JBReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora - By Marcelo");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(450, 385));
        setMinimumSize(new java.awt.Dimension(450, 385));
        setPreferredSize(new java.awt.Dimension(450, 385));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel1.setMaximumSize(new java.awt.Dimension(450, 329));
        jPanel1.setMinimumSize(new java.awt.Dimension(429, 329));

        jLabel1.setBackground(new java.awt.Color(255, 255, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CALCULADORA");

        jJanelaTexto.setBackground(new java.awt.Color(153, 153, 153));
        jJanelaTexto.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jJanelaTexto.setForeground(new java.awt.Color(0, 0, 0));
        jJanelaTexto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jJanelaTexto.setEnabled(false);

        JBZero.setBackground(new java.awt.Color(0, 0, 0));
        JBZero.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JBZero.setForeground(new java.awt.Color(204, 204, 204));
        JBZero.setText("0");
        JBZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBZeroActionPerformed(evt);
            }
        });

        JBUm1.setBackground(new java.awt.Color(0, 0, 0));
        JBUm1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JBUm1.setForeground(new java.awt.Color(204, 204, 204));
        JBUm1.setText("1");
        JBUm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBUm1ActionPerformed(evt);
            }
        });

        JBDois.setBackground(new java.awt.Color(0, 0, 0));
        JBDois.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JBDois.setForeground(new java.awt.Color(204, 204, 204));
        JBDois.setText("2");
        JBDois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBDoisActionPerformed(evt);
            }
        });

        JBVirgula.setBackground(new java.awt.Color(0, 0, 0));
        JBVirgula.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JBVirgula.setForeground(new java.awt.Color(204, 204, 204));
        JBVirgula.setText(",");
        JBVirgula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBVirgulaActionPerformed(evt);
            }
        });

        JBTres.setBackground(new java.awt.Color(0, 0, 0));
        JBTres.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JBTres.setForeground(new java.awt.Color(204, 204, 204));
        JBTres.setText("3");
        JBTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTresActionPerformed(evt);
            }
        });

        JBAdicao.setBackground(new java.awt.Color(51, 51, 51));
        JBAdicao.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JBAdicao.setForeground(new java.awt.Color(204, 204, 204));
        JBAdicao.setText("+");
        JBAdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAdicaoActionPerformed(evt);
            }
        });

        JBSubtracao.setBackground(new java.awt.Color(51, 51, 51));
        JBSubtracao.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JBSubtracao.setForeground(new java.awt.Color(204, 204, 204));
        JBSubtracao.setText("-");
        JBSubtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSubtracaoActionPerformed(evt);
            }
        });

        JBResultado.setBackground(new java.awt.Color(255, 102, 0));
        JBResultado.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        JBResultado.setText("=");
        JBResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBResultadoActionPerformed(evt);
            }
        });

        JBQuatro.setBackground(new java.awt.Color(0, 0, 0));
        JBQuatro.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JBQuatro.setForeground(new java.awt.Color(204, 204, 204));
        JBQuatro.setText("4");
        JBQuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBQuatroActionPerformed(evt);
            }
        });

        JBCinco.setBackground(new java.awt.Color(0, 0, 0));
        JBCinco.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JBCinco.setForeground(new java.awt.Color(204, 204, 204));
        JBCinco.setText("5");
        JBCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCincoActionPerformed(evt);
            }
        });

        JBSeis.setBackground(new java.awt.Color(0, 0, 0));
        JBSeis.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JBSeis.setForeground(new java.awt.Color(204, 204, 204));
        JBSeis.setText("6");
        JBSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSeisActionPerformed(evt);
            }
        });

        JBMultiplicacao.setBackground(new java.awt.Color(51, 51, 51));
        JBMultiplicacao.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JBMultiplicacao.setForeground(new java.awt.Color(204, 204, 204));
        JBMultiplicacao.setText("X");
        JBMultiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBMultiplicacaoActionPerformed(evt);
            }
        });

        JBSete.setBackground(new java.awt.Color(0, 0, 0));
        JBSete.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JBSete.setForeground(new java.awt.Color(204, 204, 204));
        JBSete.setText("7");
        JBSete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSeteActionPerformed(evt);
            }
        });

        JBOito.setBackground(new java.awt.Color(0, 0, 0));
        JBOito.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JBOito.setForeground(new java.awt.Color(204, 204, 204));
        JBOito.setText("8");
        JBOito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBOitoActionPerformed(evt);
            }
        });

        JBNove.setBackground(new java.awt.Color(0, 0, 0));
        JBNove.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JBNove.setForeground(new java.awt.Color(204, 204, 204));
        JBNove.setText("9");
        JBNove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNoveActionPerformed(evt);
            }
        });

        JBDivisao.setBackground(new java.awt.Color(51, 51, 51));
        JBDivisao.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JBDivisao.setForeground(new java.awt.Color(204, 204, 204));
        JBDivisao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/image/division.png"))); // NOI18N
        JBDivisao.setMaximumSize(new java.awt.Dimension(38, 38));
        JBDivisao.setMinimumSize(new java.awt.Dimension(38, 38));
        JBDivisao.setPreferredSize(new java.awt.Dimension(38, 38));
        JBDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBDivisaoActionPerformed(evt);
            }
        });

        JBReset.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        JBReset.setForeground(new java.awt.Color(51, 51, 51));
        JBReset.setText("CE");
        JBReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jJanelaTexto)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(JBZero, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JBVirgula, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JBAdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(JBUm1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JBDois, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JBTres, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JBSubtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(JBQuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JBCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JBSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JBMultiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(JBSete, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JBOito, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JBNove, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JBDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(JBResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(JBReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {JBAdicao, JBCinco, JBDivisao, JBDois, JBMultiplicacao, JBNove, JBOito, JBQuatro, JBResultado, JBSeis, JBSete, JBSubtracao, JBTres, JBUm1, JBVirgula});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jJanelaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JBDivisao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(JBSete)
                                .addComponent(JBOito)
                                .addComponent(JBNove)))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JBQuatro)
                            .addComponent(JBCinco)
                            .addComponent(JBSeis)
                            .addComponent(JBMultiplicacao)))
                    .addComponent(JBReset, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JBUm1)
                            .addComponent(JBDois)
                            .addComponent(JBTres)
                            .addComponent(JBSubtracao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JBAdicao)
                            .addComponent(JBVirgula)
                            .addComponent(JBZero)))
                    .addComponent(JBResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {JBAdicao, JBCinco, JBDivisao, JBDois, JBMultiplicacao, JBNove, JBOito, JBQuatro, JBSeis, JBSete, JBSubtracao, JBTres, JBUm1, JBVirgula, JBZero});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBZeroActionPerformed
        jJanelaTexto.setText(jJanelaTexto.getText() + "0"); 
    }//GEN-LAST:event_JBZeroActionPerformed

    private void JBUm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBUm1ActionPerformed
        jJanelaTexto.setText(jJanelaTexto.getText() + "1");     
    }//GEN-LAST:event_JBUm1ActionPerformed

    private void JBDoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBDoisActionPerformed
        jJanelaTexto.setText(jJanelaTexto.getText() + "2");  
    }//GEN-LAST:event_JBDoisActionPerformed

    private void JBVirgulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBVirgulaActionPerformed
        jJanelaTexto.setText(jJanelaTexto.getText() + ".");  
    }//GEN-LAST:event_JBVirgulaActionPerformed

    private void JBTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTresActionPerformed
        jJanelaTexto.setText(jJanelaTexto.getText() + "3");   
    }//GEN-LAST:event_JBTresActionPerformed

    private void JBAdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAdicaoActionPerformed
        jJanelaTexto.setText("+");  
    }//GEN-LAST:event_JBAdicaoActionPerformed

    private void JBSubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSubtracaoActionPerformed
        jJanelaTexto.setText("-");    
    }//GEN-LAST:event_JBSubtracaoActionPerformed

    private void JBResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBResultadoActionPerformed
        String[] valoresSeparados = jJanelaTexto.getText().split("\\+");
        
        for (int i = 0; 1 < valoresSeparados.length; i++){
            System.out.println("o valor é: "+valoresSeparados[i]);
        }
    }//GEN-LAST:event_JBResultadoActionPerformed

    private void JBQuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBQuatroActionPerformed
        jJanelaTexto.setText(jJanelaTexto.getText() + "4");   
    }//GEN-LAST:event_JBQuatroActionPerformed

    private void JBCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCincoActionPerformed
        jJanelaTexto.setText(jJanelaTexto.getText() + "5");   
    }//GEN-LAST:event_JBCincoActionPerformed

    private void JBSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSeisActionPerformed
        jJanelaTexto.setText(jJanelaTexto.getText() + "6");  
    }//GEN-LAST:event_JBSeisActionPerformed

    private void JBMultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBMultiplicacaoActionPerformed
        jJanelaTexto.setText("*");  
    }//GEN-LAST:event_JBMultiplicacaoActionPerformed

    private void JBSeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSeteActionPerformed
        jJanelaTexto.setText(jJanelaTexto.getText() + "7");  
    }//GEN-LAST:event_JBSeteActionPerformed

    private void JBOitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBOitoActionPerformed
        jJanelaTexto.setText(jJanelaTexto.getText() + "8");    
    }//GEN-LAST:event_JBOitoActionPerformed

    private void JBNoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNoveActionPerformed
        jJanelaTexto.setText(jJanelaTexto.getText() + "9");   
    }//GEN-LAST:event_JBNoveActionPerformed

    private void JBDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBDivisaoActionPerformed
        jJanelaTexto.setText("/");   
    }//GEN-LAST:event_JBDivisaoActionPerformed

    private void JBResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBResetActionPerformed
        jJanelaTexto.setText("");  
    }//GEN-LAST:event_JBResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAdicao;
    private javax.swing.JButton JBCinco;
    private javax.swing.JButton JBDivisao;
    private javax.swing.JButton JBDois;
    private javax.swing.JButton JBMultiplicacao;
    private javax.swing.JButton JBNove;
    private javax.swing.JButton JBOito;
    private javax.swing.JButton JBQuatro;
    private javax.swing.JButton JBReset;
    private javax.swing.JButton JBResultado;
    private javax.swing.JButton JBSeis;
    private javax.swing.JButton JBSete;
    private javax.swing.JButton JBSubtracao;
    private javax.swing.JButton JBTres;
    private javax.swing.JButton JBUm1;
    private javax.swing.JButton JBVirgula;
    private javax.swing.JButton JBZero;
    private javax.swing.JTextField jJanelaTexto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
